### PR TITLE
Update MediaMTX 

### PR DESCRIPTION
**Pull request by mrlt8**
## WebUI auth

- Default `wb_password` will now be derived from the username part of the Wyze email address instead of using a randomly generated password.
  - Example: For the email address `john123@doe.com`, the `wb_password` will be `john123`.
- Default `wb_api` will attempt to persist based on wyze account.

### NEW: `STREAM_AUTH` option to specify multiple users and paths:

- Username and password should be separated by a `:` 
- An additional `:` can be used to specify the allowed IP address for the user. 
  - **This does NOT work with docker desktop**
  - Specify multiple IPs using a comma
- Use the `@` to specify paths accessible to the user. 
  - Paths are optional for each user.  
  - Multiple paths can be specified by using a comma. If none are provided, the user will have access to all paths/streams 
- Multiple users can be specified by using  `|` as a separator 

#### EXAMPLES:
```
STREAM_AUTH=user:pass@cam-1,other-cam|second-user:password@just-one-cam|user3:pass
```

- `user:pass`  has access to `cam-1` and `other-cam`
- `second-user:password` has access to `just-one-cam`
- `user3:pass` has access to **all** paths/cameras

```
STREAM_AUTH= user:pass:192.168.0.7|::192.168.0.10|::192.168.0.15,192.168.0.20@just-one-cam
```
- `user:pass`  has access to **all** paths/cameras when streaming **from 192.168.0.7**
- No authentication required for **all** paths/cameras when streaming **from 192.168.0.10**
- No authentication required for `just-one-cam` when streaming **from 192.168.0.15** or **from 192.168.0.20**

```
STREAM_AUTH=user:pass|:@public-cam|::192.168.0.17
```
- `user:pass`  has access to **all** paths/cameras
- No authentication required for `public-cam`
- No authentication required for **all** paths/cameras when streaming **from 192.168.0.17**

---

### Recording via MediaMTX:

`RECORD_PATH` Available variables are `%path` or `{cam_name}`, `%Y` `%m` `%d` `%H` `%M` `%S` `%f` `%s` (time in strftime format).

`RECORD_LENGTH` Length of each clip. Use `s` for seconds , `h` for hours. Defaults to `60s`
`RECORD_KEEP` Delete older clips. Use `s` for seconds , `h` for hours. Set to 0s to disable automatic deletion. Defaults to `0s`

### CODE REVIEW

**Comment by JA16122000** [comment]
- /mnt/usbhdd/Record/:/record/

Changed '/record/' to '/Record/' and now it is recording ;) [On the 'latest' branche and 'previous build', this won't record at all]
But now i don't get a live stream.
Just an frozen image

HLS Stream is working fine, but WebRTC stream is not working

**Comment by mrlt8** [comment]
@JA16122000 default settings will record to `/record/ `, however, if you changed this with `RECORD_PATH` then you need to mount the location you're recording to.

**Comment by JA16122000** [comment]
Unfortunately, the WebRTC stream is not working.

HLS is working, though.

**Comment by mrlt8** [comment]
@JA16122000  WebRTC should be fixed with the latest changes. Please let me know if your run into any other issues.

**Comment by JA16122000** [comment]
> @JA16122000 WebRTC should be fixed with the latest changes. Please let me know if your run into any other issues.

Still not playing with WebRTC

docker-compose.yml looks like:

-----------------------------------


services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: mrlt8/wyze-bridge:dev
        ports:
            - 1935:1935 # RTMP
            - 8554:8554 # RTSP
            - 8888:8888 # HLS
            - 5000:5000 # WEB-UI
            - 9997:9997 # Expose port for API
            - 8889:8889 # WebRTC
            - 8189:8189/udp # WebRTC/ICE
        environment:
            - API_ID=blob
            - API_KEY=blob
            - WYZE_EMAIL=blob
            - WYZE_PASSWORD=blob
            - STREAM_AUTH=blob:blob
            - WB_AUTH=True
            - WB_USERNAME=blob
            - WB_PASSWORD=blob
            - WB_IP=192.168.178.78
            - NET_MODE=LAN
            - KEEP_BAD_FRAMES=True
            - FRESH_DATA=True
            - TZ=Europe/Amsterdam
            - RECORD_ALL=True
            - RECORD_PATH=/Record/{cam_name}
            - RECORD_FILE_NAME={cam_name}_%Y_%m_%d_%H_%M_%S
            - RECORD_LENGTH=1800s    
        volumes:
            - /mnt/usbhdd/Record/:/Record/
            - ./tokens:/tokens/

**Comment by JA16122000** [comment]
Noticed that MTX auth:

🚀 DOCKER-WYZE-BRIDGE v2.9.9 ARMV7L DEV BUILD [2024-06-24t14:25:28.918z] https://github.com/mrlt8/docker-wyze-bridge/commit/357857c8197ee863ad3752b0f29533f16249ecc7
[WyzeBridge] ♻️ Clearing local cache...
[WyzeBridge] [MTX] Custom stream auth enabled
[WyzeBridge] [MTX] Auth [blob:blob] paths='all'    <<<========= 

I noticed that 'MTX auth' is not case-sensitive for passwords. (I have capital letters, buth in the log they are NOT capital

**Comment by mrlt8** [comment]
Good catch, thanks @JA16122000!

**Comment by JA16122000** [comment]
But still not playing WebRTC 😂

**Comment by mrlt8** [comment]
It doesn't look like your cameras are even connected in your logs. Is HLS even working?

**Comment by JA16122000** [comment]
HLS is working fine

WebRTC is only an image jumping in time

LOG:


--------------------------------------------------------------

[WyzeBridge] 📖 New client reading from achtertuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:09:49] "GET /signaling/voortuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:09:49] "GET /signaling/achtertuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 📕 Client stopped reading from achtertuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:09:50] "GET /snapshot/achtertuin.jpg?1719241783904 HTTP/1.1" 200 -
[WyzeBridge] 📕 Client stopped reading from voortuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:09:50] "GET /snapshot/voortuin.jpg?1719241783903 HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:10:02] "GET /signaling/voortuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:10:02] "GET /signaling/achtertuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:10:15] "GET /signaling/voortuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:10:15] "GET /signaling/achtertuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from voortuin
[WyzeBridge] 📖 New client reading from achtertuin
[WyzeBridge] 📕 Client stopped reading from voortuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:10:17] "GET /snapshot/voortuin.jpg?1719241814641 HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from voortuin
[WyzeBridge] 📕 Client stopped reading from achtertuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:10:18] "GET /snapshot/achtertuin.jpg?1719241814642 HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from achtertuin
[WyzeBridge] 📕 Client stopped reading from voortuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:10:19] "GET /snapshot/voortuin.jpg?1719241814641 HTTP/1.1" 200 -
[WyzeBridge] 📕 Client stopped reading from achtertuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:10:20] "GET /snapshot/achtertuin.jpg?1719241814642 HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:10:29] "GET /signaling/achtertuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:10:29] "GET /signaling/voortuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:10:43] "GET /signaling/achtertuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:10:43] "GET /signaling/voortuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from achtertuin
[WyzeBridge] 📖 New client reading from voortuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:10:49] "GET /snapshot/achtertuin.jpg?1719241845265 HTTP/1.1" 200 -
[WyzeBridge] 📕 Client stopped reading from achtertuin
[WyzeBridge] 📕 Client stopped reading from voortuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:10:49] "GET /snapshot/voortuin.jpg?1719241845265 HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from achtertuin
[WyzeBridge] 📖 New client reading from voortuin
[WyzeBridge] 📕 Client stopped reading from achtertuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:10:51] "GET /snapshot/achtertuin.jpg?1719241845265 HTTP/1.1" 200 -
[WyzeBridge] 📕 Client stopped reading from voortuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:10:51] "GET /snapshot/voortuin.jpg?1719241845265 HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:10:56] "GET /signaling/achtertuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:10:56] "GET /signaling/voortuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:11:10] "GET /signaling/achtertuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:11:10] "GET /signaling/voortuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from achtertuin
[WyzeBridge] 📖 New client reading from voortuin
[WyzeBridge] 📕 Client stopped reading from voortuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:11:19] "GET /snapshot/voortuin.jpg?1719241875719 HTTP/1.1" 200 -
[WyzeBridge] 📕 Client stopped reading from achtertuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:11:20] "GET /snapshot/achtertuin.jpg?1719241875719 HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from voortuin
[WyzeBridge] 📖 New client reading from achtertuin
[WyzeBridge] 📕 Client stopped reading from voortuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:11:21] "GET /snapshot/voortuin.jpg?1719241875719 HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:11:22] "GET /snapshot/achtertuin.jpg?1719241875719 HTTP/1.1" 200 -
[WyzeBridge] 📕 Client stopped reading from achtertuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:11:23] "GET /signaling/voortuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:11:23] "GET /signaling/achtertuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:11:38] "GET /signaling/voortuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:11:38] "GET /signaling/achtertuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from voortuin
[WyzeBridge] 📖 New client reading from achtertuin
[WyzeBridge] 📕 Client stopped reading from voortuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:11:49] "GET /snapshot/voortuin.jpg?1719241906027 HTTP/1.1" 200 -
[WyzeBridge] 📕 Client stopped reading from achtertuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:11:50] "GET /snapshot/achtertuin.jpg?1719241906028 HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from voortuin
[WyzeBridge] 📖 New client reading from achtertuin
[WyzeBridge] 📕 Client stopped reading from voortuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:11:51] "GET /snapshot/voortuin.jpg?1719241906027 HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:11:52] "GET /signaling/voortuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:11:52] "GET /signaling/achtertuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 📕 Client stopped reading from achtertuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:11:52] "GET /snapshot/achtertuin.jpg?1719241906028 HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:12:06] "GET /signaling/voortuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:12:06] "GET /signaling/achtertuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from voortuin
[WyzeBridge] 📖 New client reading from achtertuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:12:19] "GET /signaling/voortuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:12:19] "GET /signaling/achtertuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 📕 Client stopped reading from voortuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:12:20] "GET /snapshot/voortuin.jpg?1719241936413 HTTP/1.1" 200 -
[WyzeBridge] 📕 Client stopped reading from achtertuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:12:20] "GET /snapshot/achtertuin.jpg?1719241936414 HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from voortuin
[WyzeBridge] 📖 New client reading from achtertuin
[WyzeBridge] 📕 Client stopped reading from achtertuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:12:22] "GET /snapshot/achtertuin.jpg?1719241936414 HTTP/1.1" 200 -
[WyzeBridge] 📕 Client stopped reading from voortuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:12:22] "GET /snapshot/voortuin.jpg?1719241936413 HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:12:33] "GET /signaling/achtertuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:12:33] "GET /signaling/voortuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:12:48] "GET /signaling/voortuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:12:48] "GET /signaling/achtertuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from voortuin
[WyzeBridge] 📖 New client reading from achtertuin
[WyzeBridge] 📕 Client stopped reading from achtertuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:12:50] "GET /snapshot/achtertuin.jpg?1719241966892 HTTP/1.1" 200 -
[WyzeBridge] 📖 New client reading from achtertuin
[WyzeBridge] 📕 Client stopped reading from achtertuin
[WyzeBridge] 173.239.217.129 - - [24/Jun/2024 17:12:52] "GET /snapshot/achtertuin.jpg?1719241966892 HTTP/1.1" 200 -

**Comment by mrlt8** [comment]
What browser? Seems to be working for me on safari/chrome/firefox

**Comment by JA16122000** [comment]
Good point

Firefox i'm using [VPN] NO WebRTC
Opera also [VPN] NO WebRTC



Chrome [NO VPN] WebRTC playing for 8 - 10 seconds, then crashing

**Comment by JA16122000** [comment]
OK, found it.
VPN must be turned OFF

So it is VPN related

**Comment by JA16122000** [comment]
'Latest' Branch will record from 1:00 till 1:30 and from 1:30 till 2:00 (So when i start the bridge on 1:18, it wil stop on 1:30 en start a new one til 2:00 en then till 2:30 and so on. Very nice!

but

'dev' branch will stop recording exactly after 1800s (30 minutes)
So when i start the bridge on 1:18, then the recording is from 1:18 till 1:48 and the next recroding from 1:48 till 2:18 etc. etc. etc.

**Comment by mrlt8** [comment]
Thanks for the feedback @JA16122000! Is the webRTC issue with the VPN only on the dev branch? Did your VPN work with the previous builds?

**Comment by JA16122000** [comment]
> Thanks for the feedback @JA16122000! Is the webRTC issue with the VPN only on the dev branch? Did your VPN work with the previous builds?

The WebRTC issue with the VPN enabled is indeed only on the 'dev' branch.

I suspect it has to do with the newer MTX variant, as it worked with older 'dev' branches with older MTX versions

**Comment by JA16122000** [comment]
> Could you post some more details about your vpn config so I can replicate the issue? Are you connecting to the bridge over a VPN or is the VPN unrelated to the bridge?

On my laptop (locally, not on the entire network), I use PIA (Private Internet Access) as a VPN.
As soon as I turn on PIA (i.e., turn on the VPN on my local laptop), I can no longer see WebRTC.
If I turn off the VPN on the laptop, WebRTC works perfectly.

Addition:

On my phone, I use a VPN tunnel so that I can use my home network (no matter where I am).
As soon as I use this VPN tunnel, I cannot see WebRTC on the phone.
If I turn off the VPN tunnel, I can see WebRTC.

----------------------------------------------
For clarity, my own network is VPN-free.

**Comment by mrlt8** [comment]
hmm, so I can kind of replicate the issue by connecting to a commercial VPN service...

|        | chrome | safari                    | firefox                   |
|--------|--------|---------------------------|---------------------------|
| dev    | yes    | no                        | yes on linux; no on macOS |
| latest | yes    | yes on linux; no on macOS | yes on linux; no on macOS |

**Comment by JA16122000** [comment]
> hmm, so I can kind of replicate the issue by connecting to a commercial VPN service...

WebRTC doesn't work with VPNs.

No matter which VPN you use.

    It doesn't work on my phone to access my home network through a VPN tunnel.
    And it also doesn't work with paid VPN services.

It seems that WebRTC is simply not discoverable from outside the network?

**Comment by mrlt8** [comment]
So are you trying to VPN back to your LAN to view the WebRTC or are you routing your traffic via a VPN while on your local network?

Chrome seems to be resilient to VPN changes for me on DEV/Latest.

**Comment by JA16122000** [comment]
> So are you trying to VPN back to your LAN to view the WebRTC or are you routing your traffic via a VPN while on your local network?
> 
> Chrome seems to be resilient to VPN changes for me on DEV/Latest.

On my LAN-network, i don't have an VPN.

PHONE:
On my phone, i'm trying to VPN back to my LAN indeed [WebRTC NOT working]
When i'm home and not using VPN back to my LAN, WebRTC is working.
When i'm home and also using VPN back to my LAN, WebRTC is NOT working.
When i'm NOT home, i cannot acces WebRTC

LAPTOP
My laptop (Local) i'm routing my traffic via VPN, then WebRTC is NOT working on any browser
My laptop (Local) when i'm not routing via VPN, then WebRTC is working.

**Comment by JA16122000** [comment]
Working without VPN.
Not working with VPN

--------------------------------------------------------------------------------------------------------------------------------------

🚀 DOCKER-WYZE-BRIDGE v2.9.10 ARMV7L DEV BUILD [2024-06-29t13:56:12.963z] 71df0c2
[WyzeBridge] ♻️ Clearing local cache...
[WyzeBridge] [MTX] Custom stream auth enabled
[WyzeBridge] [MTX] Auth [Mulderij:7316KP04] paths='all'
[WyzeBridge] 🔍 Could not find local cache for 'auth'
[WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
 * Serving Flask app 'frontend'
 * Debug mode: off
[WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.2:5000
[WyzeBridge] Press CTRL+C to quit
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:17] "GET /?video HTTP/1.1" 302 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:17] "GET /login HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:17] "GET /static/site.css HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:17] "GET /static/bulma.css HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:18] "GET /static/bulma-toast.js HTTP/1.1" 200 -
[WyzeBridge] 💾 Saving 'auth' to local cache...
[WyzeBridge] 🔍 Could not find local cache for 'user'
[WyzeBridge] ☁️ Fetching 'user' from the Wyze API...
[WyzeBridge] 💾 Saving 'user' to local cache...
[WyzeBridge] 🔍 Could not find local cache for 'cameras'
[WyzeBridge] ☁️ Fetching 'cameras' from the Wyze API...
[WyzeBridge] [API] Fetched [2] cameras
[WyzeBridge] 💾 Saving 'cameras' to local cache...
[WyzeBridge] [+] Adding Voortuin [HL_CAM3P]
[WyzeBridge] [MTX] 📹 Will record 1800s clips to /Record/voortuin/voortuin_%Y_%m_%d_%H_%M_%S.mp4
[WyzeBridge] [+] Adding Achtertuin [HL_CAM3P]
[WyzeBridge] [MTX] 📹 Will record 1800s clips to /Record/achtertuin/achtertuin_%Y_%m_%d_%H_%M_%S.mp4
[WyzeBridge] [MTX] starting MediaMTX 1.8.3
[WyzeBridge] 🎬 2 streams enabled
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:20] "GET /login HTTP/1.1" 302 -
[WyzeBridge] 🎉 Connecting to WyzeCam V3 Pro - Voortuin on 192.168.178.70
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:21] "GET / HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:21] "GET /static/bulma.css HTTP/1.1" 304 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:21] "GET /static/site.css HTTP/1.1" 304 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:21] "GET /static/bulma-toast.js HTTP/1.1" 304 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:21] "GET /static/webrtc.js HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:21] "GET /static/site.js HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:21] "GET /static/loading.svg HTTP/1.1" 200 -
[WyzeBridge] 🎉 Connecting to WyzeCam V3 Pro - Achtertuin on 192.168.178.69
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:22] "GET /api/sse_status HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:22] "GET /signaling/voortuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:22] "GET /signaling/achtertuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] ☁️ Pulling "voortuin" thumbnail to /img/voortuin.jpg
[WyzeBridge] ☁️ Pulling "achtertuin" thumbnail to /img/achtertuin.jpg
[achtertuin] 📡 Getting 180kb/s 2K stream (H264/20fps) via LAN mode (WiFi: 70%) FW: 4.58.12.9751 🔒
[voortuin] 📡 Getting 180kb/s 2K stream (H264/20fps) via LAN mode (WiFi: 61%) FW: 4.58.12.9751 🔒
[voortuin] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
[achtertuin] WARNING: Skipping wrong frame_size at start of stream [frame_size=1]
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:25] "GET /img/achtertuin.jpg HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:25] "GET /img/voortuin.jpg HTTP/1.1" 200 -
[WyzeBridge] ✅ '/voortuin stream is UP! (3/3)
[WyzeBridge] ✅ '/achtertuin stream is UP! (3/3)
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:25] "GET /img/achtertuin.jpg HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:26] "GET /img/voortuin.jpg HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:26] "GET /signaling/voortuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:27] "GET /signaling/achtertuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:36] "GET / HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:36] "GET /static/bulma.css HTTP/1.1" 304 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:36] "GET /static/site.css HTTP/1.1" 304 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:36] "GET /static/webrtc.js HTTP/1.1" 304 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:36] "GET /static/bulma-toast.js HTTP/1.1" 304 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:36] "GET /static/site.js HTTP/1.1" 304 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:37] "GET /img/achtertuin.jpg HTTP/1.1" 304 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:37] "GET /img/achtertuin.jpg HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:37] "GET /img/voortuin.jpg HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:37] "GET /api/sse_status HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:37] "GET /img/voortuin.jpg HTTP/1.1" 304 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:37] "GET /signaling/voortuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:37] "GET /signaling/achtertuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:52] "GET /signaling/voortuin?webrtc HTTP/1.1" 200 -
[WyzeBridge] 173.239.217.165 - - [29/Jun/2024 16:01:52] "GET /signaling/achtertuin?webrtc HTTP/1.1" 200 -

**Comment by mrlt8** [comment]
No changes have been made re: webrtc, so there shouldn't be any difference.

potential work around: 
```yaml
ports:
    - 8189:8189
    - 8189:8189/udp
    ...
environment:
    - MTX_WEBRTCLOCALTCPADDRESS=:8189
    ...
```

**Comment by JA16122000** [comment]
> No changes have been made re: webrtc, so there shouldn't be any difference.
> 
> potential work around:
> 
> ```yaml
> ports:
>     - 8189:8189
>     - 8189:8189/udp
>     ...
> environment:
>     - MTX_WEBRTCLOCALTCPADDRESS=:8189
>     ...
> ```

So:

ports:
    - 8189:8189
    - 8189:8189/udp
    ...
environment:
    - MTX_WEBRTCLOCALTCPADDRESS=192.168.178.78:8189
    
    
    Thats also not working
    ...

**Comment by mrlt8** [comment]
no, should be:
```
- MTX_WEBRTCLOCALTCPADDRESS=:8189
```

**Comment by JA16122000** [comment]
> no, should be:
> 
> ```
> - MTX_WEBRTCLOCALTCPADDRESS=:8189
> ```

Also tried, but doesn't work either

**Comment by mrlt8** [comment]
then you should probably open an issue with mediamtx as you seem to be having a different issue.

**Comment by JA16122000** [comment]
Where and how do I do that?
I will do that ;)
Can I refer to this topic?

**Comment by JA16122000** [comment]
This one?
https://github.com/bluenviron/mediamtx

**Comment by JA16122000** [comment]
The same as: https://github.com/bluenviron/mediamtx/issues/3522 ??

**Comment by mrlt8** [comment]
No, you already confirmed you have a different issue.

**Comment by JA16122000** [comment]
i'm excited, works fine!

**Pull request merged**
