### PR TITLE
Add audio support

### PR DESCRIPTION
**Pull request by mrlt8**

### CODE REVIEW

**Comment by mjb83** [comment]
Very excited for sound. Submitting myself as beta tester if you require one! 

I can't believe how stable this bridge is.. Very well done github peeps never cease to amaze.

**Comment by mrlt8** [comment]
Thanks @mjb83!

Wyze seems to use different audio formats on the different cams, so would appreciate it if you could test out some different ffmpeg audio format to see what works. e.g.:

```yaml
- FFAUDIO_FRONT_DOOR=s16le -ar 8000
- FFAUDIO_DRIVEWAY=g722
```

May need to git pull and build the audio branch.

**Comment by yeahme49** [comment]
My Wyze Cam v3 needed "alaw -ar 16000" for the audio settings to get it to work

**Comment by mjb83** [comment]
> Thanks @mjb83!
> 
> Wyze seems to use different audio formats on the different cams, so would appreciate it if you could test out some different ffmpeg audio format to see what works. e.g.:
> 
> ```yaml
> - FFAUDIO_FRONT_DOOR=s16le -ar 8000
> - FFAUDIO_DRIVEWAY=g722
> ```
> 
> May need to git pull and build the audio branch.



> Thanks @mjb83!
> 
> Wyze seems to use different audio formats on the different cams, so would appreciate it if you could test out some different ffmpeg audio format to see what works. e.g.:
> 
> ```yaml
> - FFAUDIO_FRONT_DOOR=s16le -ar 8000
> - FFAUDIO_DRIVEWAY=g722
> ```
> 
> May need to git pull and build the audio branch.

Hmm maybe I spoke too soon to be qualified enough to be a beta tester. I'm using the home assistant docker bridge. I'm not sure how to modify the config for wyze-bridge as the 'typical' YAML files are stored as binary .pickle format (I can't open in visual studio) and the GUI config doesn't have any options for FFAUDIO, that I can see anyway.

**Comment by mrlt8** [comment]
@mjb83 https://github.com/mrlt8/edge-repo should now have the audio images.

**Comment by mjb83** [comment]
> @mjb83 https://github.com/mrlt8/edge-repo should now have the audio images.

Nice, thanks for the link! OK I have the audio branch installed and running now, disabled the main wyze bridge install, and I can see in the logs I have audio output:

2022/04/26 10:45:58 [Camera room] 🔊 Audio Enabled - pcm/8,000Hz

but I'm not hearing it coming through the RTSP stream on my blue iris playback. I'll play around with BI settings for a bit, could have to enable something on there as well.

**Comment by mrlt8** [comment]
For compatibility, it should be converting the audio to aac with the source bitrate.

Can you try playing one of the streams in another media player like VLC?

**Comment by mjb83** [comment]
Got it working! Had to enable audio on the server side of blue iris, client side web connection wouldn't allow enable.

Working good! Want me to test anything else?

**Comment by mrlt8** [comment]
Just keep it running and let me know if it has any stability issues.

**Comment by mjb83** [comment]
I'll be honest even before using the audio fork here the uptime on the bridge in general wasn't great. My assumption is its just wifi in general isn't happy trying to feed multiple streams to my BI server and then out again to client browser... I've been tweaking here and there to keep it going but I'd say on average I need to restart the bridge at least once an hour.

**Comment by mrlt8** [comment]
You shouldn't need to restart the add-on manually as the bridge should restart the connection to each camera if the connection is lost.

Are the cameras going down and getting stuck?

**Comment by mjb83** [comment]
> You shouldn't need to restart the add-on manually as the bridge should restart the connection to each camera if the connection is lost.
> 
> Are the cameras going down and getting stuck?

The camera's will drop periodically. If / when they do they typically start a reboot cycle that keeps going until I close the Blue Iris client window that is viewing the cameras, and then manually restart the bridge. Sometimes the camera's work just fine for hours but when one of these hiccups happens I have no choice but to shut down client and restart bridge. I have 4 cameras but in my latest example only 3 of them are in the reboot cycle, example log:

2022/04/27 11:09:152022/04/27 11:09:15 [RTSP][CAM1] 📕 Client stopped reading 
[RTSP][CAM2] 📕 Client stopped reading
2022/04/27 11:09:20 [RTSP][CAM2] 📖 New client reading 
2022/04/27 11:09:20 [RTSP][CAM1] 📖 New client reading 
2022/04/27 11:09:20 [RTSP][CAM3] 📖 New client reading 
2022/04/27 11:09:30 [RTSP][CAM2] 📕 Client stopped reading
2022/04/27 11:09:30 2022/04/27 11:09:30[RTSP][CAM1] 📕 Client stopped reading 
[RTSP][CAM3] 📕 Client stopped reading

**Pull request merged**
