### PR TITLE
Add support for arm v8

### PR DESCRIPTION
**Pull request by pballandras**

### CODE REVIEW

**Comment by mrlt8** [comment]
Thanks @pballandras, but from what I can tell, arm64 should be the same as arm/v8?

https://stackoverflow.com/questions/70819028/relation-between-linux-arm64-and-linux-arm64-v8-are-these-aliases-for-each-othe

**Comment by pballandras** [comment]
Hey @mrlt8, yup that would seem to be the case uh?

My case right now is that I get an `exec format error` as the logs when I compose up. I'm using a very ratchet setup tho: Mac Mini M1 using Asahi Linux Fedora Remix so that might be the reason for all those problems. I'm fiddling with the CI in my fork to try and push to my Docker Hub an image with "arm v8", so I'll update you on that and probably will close this.

Cheers! (you're quick on the review, that's nice, thanks!)

**Comment by pballandras** [comment]
This doesn't do it, I'll have a go at building the image locally to see if I can get something. For now I'll just close this to remove you some visual noise 😉

**Comment by mrlt8** [comment]
@pballandras could you try the latest dev image? #1059

**Comment by pballandras** [comment]
Sorry I missed this!

Interesting... I will gladly volunteer as ~~lab rat~~ tester 🎉

**Comment by pballandras** [comment]
It works 🎉 
```
$ dc logs wyze-bridge
Attaching to wyze-bridge
wyze-bridge      | [WyzeBridge] WARNING: invalid escape sequence '\:'
wyze-bridge      |
wyze-bridge      | 🚀 DOCKER-WYZE-BRIDGE v2.6.0 [aarch64] [DEV BUILD] fri dec 22 16:16:28 utc 2023
wyze-bridge      |
wyze-bridge      | [WyzeBridge] [WARN] Credentials are NOT set
wyze-bridge      |  * Serving Flask app 'frontend'
wyze-bridge      |  * Debug mode: off
wyze-bridge      | [WyzeBridge] 🔍 Could not find local cache for 'auth'
wyze-bridge      | [WyzeBridge] ☁️ Fetching 'auth' from the Wyze API...
wyze-bridge      | [WyzeBridge] Credentials required to complete login!
wyze-bridge      | [WyzeBridge] Please visit the WebUI to enter your credentials.
wyze-bridge      | [WyzeBridge] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
wyze-bridge      |  * Running on all addresses (0.0.0.0)
wyze-bridge      |  * Running on http://127.0.0.1:5000
wyze-bridge      |  * Running on http://10.89.0.4:5000
wyze-bridge      | [WyzeBridge] Press CTRL+C to quit
```
Still running Mac Mini M1 using Asahi Linux Fedora Remix  which didn't work at all previously!! Great work @mrlt8 🚀

**Pull request closed without merging**
