### PR TITLE
On-demand streams

### PR DESCRIPTION
**Pull request by mrlt8**
Can be enabled with the ENV option `ON_DEMAND=True`.

### CODE REVIEW

**Comment by exiva** [comment]
Does this work on a per-camera basis?

**Comment by mrlt8** [comment]
Not right now. However, I'm thinking of defaulting to on-demand and having a per-camera keep alive option.

**Comment by exiva** [comment]
@mrlt8 that would be cool, some of my cameras don't need to be streaming all the time and taking up cpu/bandwidth and only if requested. even if a bit of a delay to connect.

**Comment by mrlt8** [comment]
If you're not using the bridge to recording locally and/or using the RTSP snapshot interval, then you should be able to use ON_DEMAND=True to cut down on unused streams.

I have ON_DEMAND=True and run the cams I need through scrypted which does the motion detection and I can still check up on the other cams on-demand through the WebUI.

**Comment by exiva** [comment]
Oh, so it'll just drop off when scrypted hasn't connected in a while. Cool. Guess don't need per-camera then.

**Pull request merged**
